LANGUAGES = {
    'ar': {
        'name': 'العربية',
        'flag': '🇸🇦',
        'code': 'ar',
        'welcome': 'مرحباً بك في بوت تعلم اللغة العربية! اختر لغتك المفضلة:',
        'main_menu': 'القائمة الرئيسية',
        'choose_level': 'اختر مستواك:',
        'choose_gender': 'اختر جنسك:',
        'choose_time': 'اختر وقت إرسال الدرس:',
        'choose_days_off': 'اختر أيام الإجازة (يمكنك اختيار يومين):',
        'summary': '📋 ملخص بياناتك:',
        'name_label': '👤 الاسم:',
        'level_label': '📚 المستوى:',
        'time_label': '⏰ وقت الدرس:',
        'days_off_label': '📅 أيام الإجازة:',
        'group_label': '👥 رابط القروب:',
        'change_name': 'تغيير الاسم',
        'change_level': 'تغيير المستوى',
        'change_time': 'تغيير الوقت',
        'change_days': 'تغيير أيام الإجازة',
        'level_a0_desc': 'مستوى A0: للمبتدئين الذين لا يعرفون الحروف العربية (4 دروس)',
        'level_a1_desc': 'مستوى A1: مبتدئ (18 درس)',
        'level_a2_desc': 'مستوى A2: ما قبل المتوسط (18 درس)',
        'level_b1_desc': 'مستوى B1: متوسط (18 درس)',
        'level_b2_desc': 'مستوى B2: فوق المتوسط (18 درس)',
        'free_lessons': '📖 الدروس المجانية: أول 5 دروس',
        'payment_info': '💰 سعر الاشتراك: 5$ للمستوى الكامل (18 درس)',
        'payment_link': 'رابط الدفع:',
        'level_test': 'اختبار تحديد المستوى:',
        'lesson_sent': '📚 تم إرسال الدرس:',
        'lesson_locked': '🔒 هذا الدرس مدفوع. اشترك الآن للحصول على جميع الدروس!',
        'payment_reminder': 'للاستمرار في التعلم، يرجى الاشتراك عبر الرابط:',
        'gender_male': 'رجل',
        'gender_female': 'إمرأة',
        'group_joined': 'تم توجيهك إلى قروب الدردشة المناسب',
        'settings_updated': '✅ تم تحديث الإعدادات بنجاح!',
        'excel_exported': '✅ تم تصدير بيانات الطلاب إلى ملف Excel',
        'ai_correction': '🤖 تصحيح الذكاء الاصطناعي:',
        'conversation_practice': '🗣️ تدريب المحادثة:',
        'writing_practice': '✍️ تدريب الكتابة:',
        'days_off_selected': '✅ تم اختيار أيام الإجازة: {}',
        'no_lesson_today': '📅 اليوم هو يوم إجازتك، لا يوجد درس اليوم',
        'choose_again': 'اختر مرة أخرى',
        'confirm': 'تأكيد',
        'cancel': 'إلغاء',
        'back': 'رجوع',
        'next': 'التالي',
        'previous': 'السابق'
    },
    'en': {
        'name': 'English',
        'flag': '🇬🇧',
        'code': 'en',
        'welcome': 'Welcome to Arabic Learning Bot! Choose your preferred language:',
        'main_menu': 'Main Menu',
        'choose_level': 'Choose your level:',
        'choose_gender': 'Choose your gender:',
        'choose_time': 'Choose lesson time:',
        'choose_days_off': 'Choose days off (you can select 2 days):',
        'summary': '📋 Your Summary:',
        'name_label': '👤 Name:',
        'level_label': '📚 Level:',
        'time_label': '⏰ Lesson Time:',
        'days_off_label': '📅 Days Off:',
        'group_label': '👥 Group Link:',
        'change_name': 'Change Name',
        'change_level': 'Change Level',
        'change_time': 'Change Time',
        'change_days': 'Change Days Off',
        'level_a0_desc': 'Level A0: Complete beginners (4 lessons)',
        'level_a1_desc': 'Level A1: Beginner (18 lessons)',
        'level_a2_desc': 'Level A2: Pre-intermediate (18 lessons)',
        'level_b1_desc': 'Level B1: Intermediate (18 lessons)',
        'level_b2_desc': 'Level B2: Upper-intermediate (18 lessons)',
        'free_lessons': '📖 Free lessons: First 5 lessons',
        'payment_info': '💰 Subscription price: 5$ for full level (18 lessons)',
        'payment_link': 'Payment link:',
        'level_test': 'Level test:',
        'lesson_sent': '📚 Lesson sent:',
        'lesson_locked': '🔒 This lesson is paid. Subscribe now to get all lessons!',
        'payment_reminder': 'To continue learning, please subscribe via the link:',
        'gender_male': 'Male',
        'gender_female': 'Female',
        'group_joined': 'You have been directed to the appropriate group',
        'settings_updated': '✅ Settings updated successfully!',
        'excel_exported': '✅ Student data exported to Excel file',
        'ai_correction': '🤖 AI Correction:',
        'conversation_practice': '🗣️ Conversation Practice:',
        'writing_practice': '✍️ Writing Practice:',
        'days_off_selected': '✅ Days off selected: {}',
        'no_lesson_today': '📅 Today is your day off, no lesson today',
        'choose_again': 'Choose again',
        'confirm': 'Confirm',
        'cancel': 'Cancel',
        'back': 'Back',
        'next': 'Next',
        'previous': 'Previous'
    },
    'tr': {
        'name': 'Türkçe',
        'flag': '🇹🇷',
        'code': 'tr',
        'welcome': 'Arapça Öğrenme Botuna Hoş Geldiniz! Tercih ettiğiniz dili seçin:',
        'main_menu': 'Ana Menü',
        'choose_level': 'Seviyenizi seçin:',
        'choose_gender': 'Cinsiyetinizi seçin:',
        'choose_time': 'Ders saatini seçin:',
        'choose_days_off': 'İzin günlerini seçin (2 gün seçebilirsiniz):',
        'summary': '📋 Özetiniz:',
        'name_label': '👤 İsim:',
        'level_label': '📚 Seviye:',
        'time_label': '⏰ Ders Saati:',
        'days_off_label': '📅 İzin Günleri:',
        'group_label': '👥 Grup Bağlantısı:',
        'change_name': 'İsim Değiştir',
        'change_level': 'Seviye Değiştir',
        'change_time': 'Saat Değiştir',
        'change_days': 'İzin Günlerini Değiştir',
        'level_a0_desc': 'Seviye A0: Harfleri bilmeyen başlangıç seviyesi (4 ders)',
        'level_a1_desc': 'Seviye A1: Başlangıç (18 ders)',
        'level_a2_desc': 'Seviye A2: Orta öncesi (18 ders)',
        'level_b1_desc': 'Seviye B1: Orta (18 ders)',
        'level_b2_desc': 'Seviye B2: Orta üstü (18 ders)',
        'free_lessons': '📖 Ücretsiz dersler: İlk 5 ders',
        'payment_info': '💰 Abonelik ücreti: Tam seviye için 5$ (18 ders)',
        'payment_link': 'Ödeme bağlantısı:',
        'level_test': 'Seviye testi:',
        'lesson_sent': '📚 Ders gönderildi:',
        'lesson_locked': '🔒 Bu ders ücretlidir. Tüm dersler için abone olun!',
        'payment_reminder': 'Öğrenmeye devam etmek için lütfen bağlantıdan abone olun:',
        'gender_male': 'Erkek',
        'gender_female': 'Kadın',
        'group_joined': 'Uygun gruba yönlendirildiniz',
        'settings_updated': '✅ Ayarlar başarıyla güncellendi!',
        'excel_exported': '✅ Öğrenci verileri Excel dosyasına aktarıldı',
        'ai_correction': '🤖 Yapay Zeka Düzeltmesi:',
        'conversation_practice': '🗣️ Konuşma Pratiği:',
        'writing_practice': '✍️ Yazma Pratiği:',
        'days_off_selected': '✅ İzin günleri seçildi: {}',
        'no_lesson_today': '📅 Bugün izin gününüz, ders yok',
        'choose_again': 'Tekrar seç',
        'confirm': 'Onayla',
        'cancel': 'İptal',
        'back': 'Geri',
        'next': 'İleri',
        'previous': 'Önceki'
    },
    'es': {
        'name': 'Español',
        'flag': '🇪🇸',
        'code': 'es',
        'welcome': '¡Bienvenido al Bot de Aprendizaje de Árabe! Elige tu idioma preferido:',
        'main_menu': 'Menú Principal',
        'choose_level': 'Elige tu nivel:',
        'choose_gender': 'Elige tu género:',
        'choose_time': 'Elige la hora de la lección:',
        'choose_days_off': 'Elige días de descanso (puedes seleccionar 2 días):',
        'summary': '📋 Tu Resumen:',
        'name_label': '👤 Nombre:',
        'level_label': '📚 Nivel:',
        'time_label': '⏰ Hora de Lección:',
        'days_off_label': '📅 Días de Descanso:',
        'group_label': '👥 Enlace del Grupo:',
        'change_name': 'Cambiar Nombre',
        'change_level': 'Cambiar Nivel',
        'change_time': 'Cambiar Hora',
        'change_days': 'Cambiar Días de Descanso',
        'level_a0_desc': 'Nivel A0: Principiante absoluto (4 lecciones)',
        'level_a1_desc': 'Nivel A1: Principiante (18 lecciones)',
        'level_a2_desc': 'Nivel A2: Pre-intermedio (18 lecciones)',
        'level_b1_desc': 'Nivel B1: Intermedio (18 lecciones)',
        'level_b2_desc': 'Nivel B2: Intermedio-alto (18 lecciones)',
        'free_lessons': '📖 Lecciones gratuitas: Primeras 5 lecciones',
        'payment_info': '💰 Precio de suscripción: 5$ por nivel completo (18 lecciones)',
        'payment_link': 'Enlace de pago:',
        'level_test': 'Examen de nivel:',
        'lesson_sent': '📚 Lección enviada:',
        'lesson_locked': '🔒 Esta lección es de pago. ¡Suscríbete ahora para obtener todas las lecciones!',
        'payment_reminder': 'Para continuar aprendiendo, suscríbete a través del enlace:',
        'gender_male': 'Hombre',
        'gender_female': 'Mujer',
        'group_joined': 'Has sido dirigido al grupo apropiado',
        'settings_updated': '✅ ¡Configuración actualizada con éxito!',
        'excel_exported': '✅ Datos de estudiantes exportados a Excel',
        'ai_correction': '🤖 Corrección IA:',
        'conversation_practice': '🗣️ Práctica de Conversación:',
        'writing_practice': '✍️ Práctica de Escritura:',
        'days_off_selected': '✅ Días de descanso seleccionados: {}',
        'no_lesson_today': '📅 Hoy es tu día de descanso, no hay lección',
        'choose_again': 'Elige de nuevo',
        'confirm': 'Confirmar',
        'cancel': 'Cancelar',
        'back': 'Atrás',
        'next': 'Siguiente',
        'previous': 'Anterior'
    },
    'fr': {
        'name': 'Français',
        'flag': '🇫🇷',
        'code': 'fr',
        'welcome': 'Bienvenue sur le Bot d\'Apprentissage de l\'Arabe ! Choisissez votre langue préférée :',
        'main_menu': 'Menu Principal',
        'choose_level': 'Choisissez votre niveau :',
        'choose_gender': 'Choisissez votre genre :',
        'choose_time': 'Choisissez l\'heure de la leçon :',
        'choose_days_off': 'Choisissez vos jours de repos (vous pouvez en sélectionner 2) :',
        'summary': '📋 Votre Résumé :',
        'name_label': '👤 Nom :',
        'level_label': '📚 Niveau :',
        'time_label': '⏰ Heure de la Leçon :',
        'days_off_label': '📅 Jours de Repos :',
        'group_label': '👥 Lien du Groupe :',
        'change_name': 'Changer le Nom',
        'change_level': 'Changer le Niveau',
        'change_time': 'Changer l\'Heure',
        'change_days': 'Changer les Jours de Repos',
        'level_a0_desc': 'Niveau A0 : Débutant complet (4 leçons)',
        'level_a1_desc': 'Niveau A1 : Débutant (18 leçons)',
        'level_a2_desc': 'Niveau A2 : Pré-intermédiaire (18 leçons)',
        'level_b1_desc': 'Niveau B1 : Intermédiaire (18 leçons)',
        'level_b2_desc': 'Niveau B2 : Intermédiaire-supérieur (18 leçons)',
        'free_lessons': '📖 Leçons gratuites : 5 premières leçons',
        'payment_info': '💰 Prix d\'abonnement : 5$ pour le niveau complet (18 leçons)',
        'payment_link': 'Lien de paiement :',
        'level_test': 'Test de niveau :',
        'lesson_sent': '📚 Leçon envoyée :',
        'lesson_locked': '🔒 Cette leçon est payante. Abonnez-vous maintenant pour obtenir toutes les leçons !',
        'payment_reminder': 'Pour continuer à apprendre, abonnez-vous via le lien :',
        'gender_male': 'Homme',
        'gender_female': 'Femme',
        'group_joined': 'Vous avez été dirigé vers le groupe approprié',
        'settings_updated': '✅ Paramètres mis à jour avec succès !',
        'excel_exported': '✅ Données des étudiants exportées vers Excel',
        'ai_correction': '🤖 Correction IA :',
        'conversation_practice': '🗣️ Pratique de Conversation :',
        'writing_practice': '✍️ Pratique d\'Écriture :',
        'days_off_selected': '✅ Jours de repos sélectionnés : {}',
        'no_lesson_today': '📅 Aujourd\'hui est votre jour de repos, pas de leçon',
        'choose_again': 'Choisissez à nouveau',
        'confirm': 'Confirmer',
        'cancel': 'Annuler',
        'back': 'Retour',
        'next': 'Suivant',
        'previous': 'Précédent'
    },
    'ru': {
        'name': 'Русский',
        'flag': '🇷🇺',
        'code': 'ru',
        'welcome': 'Добро пожаловать в бот по изучению арабского языка! Выберите предпочитаемый язык:',
        'main_menu': 'Главное меню',
        'choose_level': 'Выберите ваш уровень:',
        'choose_gender': 'Выберите ваш пол:',
        'choose_time': 'Выберите время урока:',
        'choose_days_off': 'Выберите выходные дни (можно выбрать 2 дня):',
        'summary': '📋 Ваша сводка:',
        'name_label': '👤 Имя:',
        'level_label': '📚 Уровень:',
        'time_label': '⏰ Время урока:',
        'days_off_label': '📅 Выходные дни:',
        'group_label': '👥 Ссылка на группу:',
        'change_name': 'Изменить имя',
        'change_level': 'Изменить уровень',
        'change_time': 'Изменить время',
        'change_days': 'Изменить выходные дни',
        'level_a0_desc': 'Уровень A0: Полный новичок (4 урока)',
        'level_a1_desc': 'Уровень A1: Начальный (18 уроков)',
        'level_a2_desc': 'Уровень A2: Ниже среднего (18 уроков)',
        'level_b1_desc': 'Уровень B1: Средний (18 уроков)',
        'level_b2_desc': 'Уровень B2: Выше среднего (18 уроков)',
        'free_lessons': '📖 Бесплатные уроки: Первые 5 уроков',
        'payment_info': '💰 Стоимость подписки: 5$ за полный уровень (18 уроков)',
        'payment_link': 'Ссылка на оплату:',
        'level_test': 'Тест на уровень:',
        'lesson_sent': '📚 Урок отправлен:',
        'lesson_locked': '🔒 Этот урок платный. Подпишитесь сейчас, чтобы получить все уроки!',
        'payment_reminder': 'Чтобы продолжить обучение, подпишитесь по ссылке:',
        'gender_male': 'Мужчина',
        'gender_female': 'Женщина',
        'group_joined': 'Вы направлены в соответствующую группу',
        'settings_updated': '✅ Настройки успешно обновлены!',
        'excel_exported': '✅ Данные студентов экспортированы в Excel',
        'ai_correction': '🤖 Исправление ИИ:',
        'conversation_practice': '🗣️ Практика разговора:',
        'writing_practice': '✍️ Практика письма:',
        'days_off_selected': '✅ Выбраны выходные дни: {}',
        'no_lesson_today': '📅 Сегодня ваш выходной, урока нет',
        'choose_again': 'Выберите снова',
        'confirm': 'Подтвердить',
        'cancel': 'Отмена',
        'back': 'Назад',
        'next': 'Далее',
        'previous': 'Назад'
    },
    'zh': {
        'name': '中文',
        'flag': '🇨🇳',
        'code': 'zh',
        'welcome': '欢迎来到阿拉伯语学习机器人！选择您的首选语言：',
        'main_menu': '主菜单',
        'choose_level': '选择您的水平：',
        'choose_gender': '选择您的性别：',
        'choose_time': '选择课程时间：',
        'choose_days_off': '选择休息日（可选择2天）：',
        'summary': '📋 您的摘要：',
        'name_label': '👤 姓名：',
        'level_label': '📚 水平：',
        'time_label': '⏰ 课程时间：',
        'days_off_label': '📅 休息日：',
        'group_label': '👥 群组链接：',
        'change_name': '更改姓名',
        'change_level': '更改水平',
        'change_time': '更改时间',
        'change_days': '更改休息日',
        'level_a0_desc': 'A0级：完全初学者（4课）',
        'level_a1_desc': 'A1级：初级（18课）',
        'level_a2_desc': 'A2级：初级以上（18课）',
        'level_b1_desc': 'B1级：中级（18课）',
        'level_b2_desc': 'B2级：中高级（18课）',
        'free_lessons': '📖 免费课程：前5课',
        'payment_info': '💰 订阅价格：完整水平5美元（18课）',
        'payment_link': '付款链接：',
        'level_test': '水平测试：',
        'lesson_sent': '📚 课程已发送：',
        'lesson_locked': '🔒 此课程为付费课程。立即订阅获取所有课程！',
        'payment_reminder': '要继续学习，请通过链接订阅：',
        'gender_male': '男性',
        'gender_female': '女性',
        'group_joined': '您已被引导到适当的群组',
        'settings_updated': '✅ 设置已成功更新！',
        'excel_exported': '✅ 学生数据已导出到Excel文件',
        'ai_correction': '🤖 AI修正：',
        'conversation_practice': '🗣️ 对话练习：',
        'writing_practice': '✍️ 写作练习：',
        'days_off_selected': '✅ 已选择休息日：{}',
        'no_lesson_today': '📅 今天是您的休息日，没有课程',
        'choose_again': '重新选择',
        'confirm': '确认',
        'cancel': '取消',
        'back': '返回',
        'next': '下一步',
        'previous': '上一步'
    },
    'ur': {
        'name': 'اردو',
        'flag': '🇵🇰',
        'code': 'ur',
        'welcome': 'عربی سیکھنے والے بوٹ میں خوش آمدید! اپنی پسندیدہ زبان منتخب کریں:',
        'main_menu': 'مرکزی مینو',
        'choose_level': 'اپنی سطح منتخب کریں:',
        'choose_gender': 'اپنی جنس منتخب کریں:',
        'choose_time': 'سبق کا وقت منتخب کریں:',
        'choose_days_off': 'چھٹی کے دن منتخب کریں (آپ 2 دن منتخب کر سکتے ہیں):',
        'summary': '📋 آپ کا خلاصہ:',
        'name_label': '👤 نام:',
        'level_label': '📚 سطح:',
        'time_label': '⏰ سبق کا وقت:',
        'days_off_label': '📅 چھٹی کے دن:',
        'group_label': '👥 گروپ لنک:',
        'change_name': 'نام تبدیل کریں',
        'change_level': 'سطح تبدیل کریں',
        'change_time': 'وقت تبدیل کریں',
        'change_days': 'چھٹی کے دن تبدیل کریں',
        'level_a0_desc': 'سطح A0: مکمل ابتدائی (4 اسباق)',
        'level_a1_desc': 'سطح A1: ابتدائی (18 اسباق)',
        'level_a2_desc': 'سطح A2: ابتدائی سے اوپر (18 اسباق)',
        'level_b1_desc': 'سطح B1: متوسط (18 اسباق)',
        'level_b2_desc': 'سطح B2: متوسط سے اوپر (18 اسباق)',
        'free_lessons': '📖 مفت اسباق: پہلے 5 اسباق',
        'payment_info': '💰 رکنیت کی قیمت: مکمل سطح کے لیے 5$ (18 اسباق)',
        'payment_link': 'ادائیگی کا لنک:',
        'level_test': 'سطح کا ٹیسٹ:',
        'lesson_sent': '📚 سبق بھیجا گیا:',
        'lesson_locked': '🔒 یہ سبق ادا شدہ ہے۔ تمام اسباق کے لیے ابھی رکنیت حاصل کریں!',
        'payment_reminder': 'سیکھنا جاری رکھنے کے لیے، براہ کرم لنک کے ذریعے رکنیت حاصل کریں:',
        'gender_male': 'مرد',
        'gender_female': 'خاتون',
        'group_joined': 'آپ کو مناسب گروپ میں بھیج دیا گیا ہے',
        'settings_updated': '✅ ترتیبات کامیابی سے اپ ڈیٹ ہو گئیں!',
        'excel_exported': '✅ طلباء کا ڈیٹا ایکسل فائل میں برآمد کر دیا گیا',
        'ai_correction': '🤖 اے آئی تصحیح:',
        'conversation_practice': '🗣️ گفتگو کی مشق:',
        'writing_practice': '✍️ تحریر کی مشق:',
        'days_off_selected': '✅ چھٹی کے دن منتخب: {}',
        'no_lesson_today': '📅 آج آپ کا چھٹی کا دن ہے، آج کوئی سبق نہیں',
        'choose_again': 'دوبارہ منتخب کریں',
        'confirm': 'تصدیق کریں',
        'cancel': 'منسوخ کریں',
        'back': 'واپس',
        'next': 'اگلا',
        'previous': 'پچھلا'
    },
    'hi': {
        'name': 'हिंदी',
        'flag': '🇮🇳',
        'code': 'hi',
        'welcome': 'अरबी सीखने वाले बॉट में आपका स्वागत है! अपनी पसंदीदा भाषा चुनें:',
        'main_menu': 'मुख्य मेनू',
        'choose_level': 'अपना स्तर चुनें:',
        'choose_gender': 'अपना लिंग चुनें:',
        'choose_time': 'पाठ का समय चुनें:',
        'choose_days_off': 'छुट्टी के दिन चुनें (आप 2 दिन चुन सकते हैं):',
        'summary': '📋 आपका सारांश:',
        'name_label': '👤 नाम:',
        'level_label': '📚 स्तर:',
        'time_label': '⏰ पाठ का समय:',
        'days_off_label': '📅 छुट्टी के दिन:',
        'group_label': '👥 ग्रुप लिंक:',
        'change_name': 'नाम बदलें',
        'change_level': 'स्तर बदलें',
        'change_time': 'समय बदलें',
        'change_days': 'छुट्टी के दिन बदलें',
        'level_a0_desc': 'स्तर A0: पूर्ण शुरुआती (4 पाठ)',
        'level_a1_desc': 'स्तर A1: शुरुआती (18 पाठ)',
        'level_a2_desc': 'स्तर A2: प्रारंभिक-मध्यवर्ती (18 पाठ)',
        'level_b1_desc': 'स्तर B1: मध्यवर्ती (18 पाठ)',
        'level_b2_desc': 'स्तर B2: उच्च-मध्यवर्ती (18 पाठ)',
        'free_lessons': '📖 मुफ्त पाठ: पहले 5 पाठ',
        'payment_info': '💰 सदस्यता मूल्य: पूर्ण स्तर के लिए 5$ (18 पाठ)',
        'payment_link': 'भुगतान लिंक:',
        'level_test': 'स्तर परीक्षण:',
        'lesson_sent': '📚 पाठ भेजा गया:',
        'lesson_locked': '🔒 यह पाठ सशुल्क है। सभी पाठ प्राप्त करने के लिए अभी सदस्यता लें!',
        'payment_reminder': 'सीखना जारी रखने के लिए, कृपया लिंक के माध्यम से सदस्यता लें:',
        'gender_male': 'पुरुष',
        'gender_female': 'महिला',
        'group_joined': 'आपको उपयुक्त समूह में भेज दिया गया है',
        'settings_updated': '✅ सेटिंग्स सफलतापूर्वक अपडेट की गईं!',
        'excel_exported': '✅ छात्र डेटा Excel फ़ाइल में निर्यात किया गया',
        'ai_correction': '🤖 AI सुधार:',
        'conversation_practice': '🗣️ बातचीत अभ्यास:',
        'writing_practice': '✍️ लेखन अभ्यास:',
        'days_off_selected': '✅ छुट्टी के दिन चुने गए: {}',
        'no_lesson_today': '📅 आज आपका छुट्टी का दिन है, आज कोई पाठ नहीं',
        'choose_again': 'फिर से चुनें',
        'confirm': 'पुष्टि करें',
        'cancel': 'रद्द करें',
        'back': 'वापस',
        'next': 'अगला',
        'previous': 'पिछला'
    },
    'fa': {
        'name': 'فارسی',
        'flag': '🇮🇷',
        'code': 'fa',
        'welcome': 'به ربات آموزش زبان عربی خوش آمدید! زبان مورد نظر خود را انتخاب کنید:',
        'main_menu': 'منوی اصلی',
        'choose_level': 'سطح خود را انتخاب کنید:',
        'choose_gender': 'جنسیت خود را انتخاب کنید:',
        'choose_time': 'زمان درس را انتخاب کنید:',
        'choose_days_off': 'روزهای تعطیل را انتخاب کنید (می‌توانید ۲ روز انتخاب کنید):',
        'summary': '📋 خلاصه شما:',
        'name_label': '👤 نام:',
        'level_label': '📚 سطح:',
        'time_label': '⏰ زمان درس:',
        'days_off_label': '📅 روزهای تعطیل:',
        'group_label': '👥 لینک گروه:',
        'change_name': 'تغییر نام',
        'change_level': 'تغییر سطح',
        'change_time': 'تغییر زمان',
        'change_days': 'تغییر روزهای تعطیل',
        'level_a0_desc': 'سطح A0: مبتدی کامل (۴ درس)',
        'level_a1_desc': 'سطح A1: مبتدی (۱۸ درس)',
        'level_a2_desc': 'سطح A2: پیش‌متوسط (۱۸ درس)',
        'level_b1_desc': 'سطح B1: متوسط (۱۸ درس)',
        'level_b2_desc': 'سطح B2: فوق متوسط (۱۸ درس)',
        'free_lessons': '📖 دروس رایگان: ۵ درس اول',
        'payment_info': '💰 قیمت اشتراک: ۵$ برای سطح کامل (۱۸ درس)',
        'payment_link': 'لینک پرداخت:',
        'level_test': 'آزمون تعیین سطح:',
        'lesson_sent': '📚 درس ارسال شد:',
        'lesson_locked': '🔒 این درس پولی است. برای دریافت همه دروس، اشتراک بخرید!',
        'payment_reminder': 'برای ادامه یادگیری، لطفاً از طریق لینک اشتراک بخرید:',
        'gender_male': 'مرد',
        'gender_female': 'زن',
        'group_joined': 'شما به گروه مناسب هدایت شدید',
        'settings_updated': '✅ تنظیمات با موفقیت به‌روزرسانی شد!',
        'excel_exported': '✅ داده‌های دانشجویان به فایل اکسل صادر شد',
        'ai_correction': '🤖 تصحیح هوش مصنوعی:',
        'conversation_practice': '🗣️ تمرین مکالمه:',
        'writing_practice': '✍️ تمرین نوشتن:',
        'days_off_selected': '✅ روزهای تعطیل انتخاب شد: {}',
        'no_lesson_today': '📅 امروز روز تعطیل شماست، درسی وجود ندارد',
        'choose_again': 'دوباره انتخاب کنید',
        'confirm': 'تأیید',
        'cancel': 'لغو',
        'back': 'بازگشت',
        'next': 'بعدی',
        'previous': 'قبلی'
    },
    'id': {
        'name': 'Bahasa Indonesia',
        'flag': '🇮🇩',
        'code': 'id',
        'welcome': 'Selamat datang di Bot Belajar Bahasa Arab! Pilih bahasa preferensi Anda:',
        'main_menu': 'Menu Utama',
        'choose_level': 'Pilih level Anda:',
        'choose_gender': 'Pilih jenis kelamin Anda:',
        'choose_time': 'Pilih waktu pelajaran:',
        'choose_days_off': 'Pilih hari libur (Anda dapat memilih 2 hari):',
        'summary': '📋 Ringkasan Anda:',
        'name_label': '👤 Nama:',
        'level_label': '📚 Level:',
        'time_label': '⏰ Waktu Pelajaran:',
        'days_off_label': '📅 Hari Libur:',
        'group_label': '👥 Link Grup:',
        'change_name': 'Ubah Nama',
        'change_level': 'Ubah Level',
        'change_time': 'Ubah Waktu',
        'change_days': 'Ubah Hari Libur',
        'level_a0_desc': 'Level A0: Pemula total (4 pelajaran)',
        'level_a1_desc': 'Level A1: Pemula (18 pelajaran)',
        'level_a2_desc': 'Level A2: Pra-menengah (18 pelajaran)',
        'level_b1_desc': 'Level B1: Menengah (18 pelajaran)',
        'level_b2_desc': 'Level B2: Menengah-atas (18 pelajaran)',
        'free_lessons': '📖 Pelajaran gratis: 5 pelajaran pertama',
        'payment_info': '💰 Harga langganan: 5$ untuk level penuh (18 pelajaran)',
        'payment_link': 'Link pembayaran:',
        'level_test': 'Tes level:',
        'lesson_sent': '📚 Pelajaran dikirim:',
        'lesson_locked': '🔒 Pelajaran ini berbayar. Berlangganan sekarang untuk mendapatkan semua pelajaran!',
        'payment_reminder': 'Untuk melanjutkan belajar, silakan berlangganan melalui link:',
        'gender_male': 'Pria',
        'gender_female': 'Wanita',
        'group_joined': 'Anda telah diarahkan ke grup yang sesuai',
        'settings_updated': '✅ Pengaturan berhasil diperbarui!',
        'excel_exported': '✅ Data siswa diekspor ke file Excel',
        'ai_correction': '🤖 Koreksi AI:',
        'conversation_practice': '🗣️ Latihan Percakapan:',
        'writing_practice': '✍️ Latihan Menulis:',
        'days_off_selected': '✅ Hari libur dipilih: {}',
        'no_lesson_today': '📅 Hari ini adalah hari libur Anda, tidak ada pelajaran',
        'choose_again': 'Pilih lagi',
        'confirm': 'Konfirmasi',
        'cancel': 'Batal',
        'back': 'Kembali',
        'next': 'Selanjutnya',
        'previous': 'Sebelumnya'
    }
}

LANGUAGE_CODES = ['ar', 'en', 'tr', 'es', 'fr', 'ru', 'zh', 'ur', 'hi', 'fa', 'id']
